// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum ExecutionAction {
  listApps,
  openApp,
  inspectUi,
  clickNode,
  scroll,
  inputText,
  readFile,
  writeFile,
  listFiles,
  captureScreen,
  performGestures,
  controlDisplay,
}

enum ExecutionStatus { succeeded, failed, cancelled }

enum ChannelError {
  permissionRequired,
  unavailable,
  targetChanged,
  invalidArguments,
  timeout,
  executionFailed,
  cancelled,
}

enum ProgressKind { stage, progress }

enum ConfirmationDecision { approve, reject, stop }

enum ApplicationListMode { blacklist, whitelist }

enum PermissionScreen { notifications, accessibility, applications }

enum TaskPanelPhase {
  waitingModel,
  thinking,
  responding,
  preparingTool,
  executingTool,
  waitingUser,
}

enum TaskPanelMessageKind { reasoning, text, tool }

/// 机器校验的目标，不使用动作摘要代替目标身份。节点只在对应快照内有效。
class ExecutionTarget {
  ExecutionTarget({
    this.packageName,
    this.windowId,
    this.snapshotId,
    this.nodeId,
    this.uri,
  });

  String? packageName;

  int? windowId;

  String? snapshotId;

  String? nodeId;

  String? uri;

  List<Object?> _toList() {
    return <Object?>[packageName, windowId, snapshotId, nodeId, uri];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionTarget decode(Object result) {
    result as List<Object?>;
    return ExecutionTarget(
      packageName: result[0] as String?,
      windowId: result[1] as int?,
      snapshotId: result[2] as String?,
      nodeId: result[3] as String?,
      uri: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionTarget || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) &&
        _deepEquals(windowId, other.windowId) &&
        _deepEquals(snapshotId, other.snapshotId) &&
        _deepEquals(nodeId, other.nodeId) &&
        _deepEquals(uri, other.uri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionTarget(packageName: $packageName, windowId: $windowId, snapshotId: $snapshotId, nodeId: $nodeId, uri: $uri)';
  }
}

class ExecutionRequest {
  ExecutionRequest({
    required this.runId,
    required this.toolCallId,
    required this.action,
    required this.arguments,
    required this.target,
    required this.timeoutMs,
  });

  String runId;

  String toolCallId;

  ExecutionAction action;

  Map<String, Object?> arguments;

  ExecutionTarget target;

  int timeoutMs;

  List<Object?> _toList() {
    return <Object?>[runId, toolCallId, action, arguments, target, timeoutMs];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionRequest decode(Object result) {
    result as List<Object?>;
    return ExecutionRequest(
      runId: result[0]! as String,
      toolCallId: result[1]! as String,
      action: result[2]! as ExecutionAction,
      arguments: (result[3]! as Map<Object?, Object?>).cast<String, Object?>(),
      target: result[4]! as ExecutionTarget,
      timeoutMs: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) &&
        _deepEquals(toolCallId, other.toolCallId) &&
        _deepEquals(action, other.action) &&
        _deepEquals(arguments, other.arguments) &&
        _deepEquals(target, other.target) &&
        _deepEquals(timeoutMs, other.timeoutMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionRequest(runId: $runId, toolCallId: $toolCallId, action: $action, arguments: $arguments, target: $target, timeoutMs: $timeoutMs)';
  }
}

class ExecutionArtifact {
  ExecutionArtifact({
    required this.uri,
    required this.name,
    required this.size,
    this.sha256,
    this.localPath,
  });

  String uri;

  String name;

  int size;

  String? sha256;

  String? localPath;

  List<Object?> _toList() {
    return <Object?>[uri, name, size, sha256, localPath];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionArtifact decode(Object result) {
    result as List<Object?>;
    return ExecutionArtifact(
      uri: result[0]! as String,
      name: result[1]! as String,
      size: result[2]! as int,
      sha256: result[3] as String?,
      localPath: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionArtifact || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(name, other.name) &&
        _deepEquals(size, other.size) &&
        _deepEquals(sha256, other.sha256) &&
        _deepEquals(localPath, other.localPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionArtifact(uri: $uri, name: $name, size: $size, sha256: $sha256, localPath: $localPath)';
  }
}

class ExecutionResult {
  ExecutionResult({
    required this.toolCallId,
    required this.status,
    required this.result,
    required this.artifacts,
    this.error,
  });

  String toolCallId;

  ExecutionStatus status;

  Map<String, Object?> result;

  List<ExecutionArtifact> artifacts;

  ChannelError? error;

  List<Object?> _toList() {
    return <Object?>[toolCallId, status, result, artifacts, error];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionResult decode(Object result) {
    result as List<Object?>;
    return ExecutionResult(
      toolCallId: result[0]! as String,
      status: result[1]! as ExecutionStatus,
      result: (result[2]! as Map<Object?, Object?>).cast<String, Object?>(),
      artifacts: (result[3]! as List<Object?>).cast<ExecutionArtifact>(),
      error: result[4] as ChannelError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(toolCallId, other.toolCallId) &&
        _deepEquals(status, other.status) &&
        _deepEquals(result, other.result) &&
        _deepEquals(artifacts, other.artifacts) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionResult(toolCallId: $toolCallId, status: $status, result: $result, artifacts: $artifacts, error: $error)';
  }
}

class ExecutionProgress {
  ExecutionProgress({
    required this.toolCallId,
    required this.sequence,
    required this.kind,
    required this.payload,
  });

  String toolCallId;

  int sequence;

  ProgressKind kind;

  String payload;

  List<Object?> _toList() {
    return <Object?>[toolCallId, sequence, kind, payload];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionProgress decode(Object result) {
    result as List<Object?>;
    return ExecutionProgress(
      toolCallId: result[0]! as String,
      sequence: result[1]! as int,
      kind: result[2]! as ProgressKind,
      payload: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(toolCallId, other.toolCallId) &&
        _deepEquals(sequence, other.sequence) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(payload, other.payload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionProgress(toolCallId: $toolCallId, sequence: $sequence, kind: $kind, payload: $payload)';
  }
}

class ExecutionCapabilities {
  ExecutionCapabilities({
    required this.actions,
    required this.notificationsAllowed,
    required this.activityResumed,
    this.accessibilityConnected = false,
  });

  List<ExecutionAction> actions;

  bool notificationsAllowed;

  bool activityResumed;

  bool accessibilityConnected;

  List<Object?> _toList() {
    return <Object?>[
      actions,
      notificationsAllowed,
      activityResumed,
      accessibilityConnected,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionCapabilities decode(Object result) {
    result as List<Object?>;
    return ExecutionCapabilities(
      actions: (result[0]! as List<Object?>).cast<ExecutionAction>(),
      notificationsAllowed: result[1]! as bool,
      activityResumed: result[2]! as bool,
      accessibilityConnected: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(actions, other.actions) &&
        _deepEquals(notificationsAllowed, other.notificationsAllowed) &&
        _deepEquals(activityResumed, other.activityResumed) &&
        _deepEquals(accessibilityConnected, other.accessibilityConnected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionCapabilities(actions: $actions, notificationsAllowed: $notificationsAllowed, activityResumed: $activityResumed, accessibilityConnected: $accessibilityConnected)';
  }
}

class ExecutionSession {
  ExecutionSession({
    required this.runId,
    required this.deviceTask,
    required this.fileUris,
    required this.appPolicy,
    required this.currentAppPolicy,
  });

  String runId;

  bool deviceTask;

  List<String> fileUris;

  ApplicationPolicy appPolicy;

  ApplicationPolicy currentAppPolicy;

  List<Object?> _toList() {
    return <Object?>[runId, deviceTask, fileUris, appPolicy, currentAppPolicy];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionSession decode(Object result) {
    result as List<Object?>;
    return ExecutionSession(
      runId: result[0]! as String,
      deviceTask: result[1]! as bool,
      fileUris: (result[2]! as List<Object?>).cast<String>(),
      appPolicy: result[3]! as ApplicationPolicy,
      currentAppPolicy: result[4]! as ApplicationPolicy,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) &&
        _deepEquals(deviceTask, other.deviceTask) &&
        _deepEquals(fileUris, other.fileUris) &&
        _deepEquals(appPolicy, other.appPolicy) &&
        _deepEquals(currentAppPolicy, other.currentAppPolicy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionSession(runId: $runId, deviceTask: $deviceTask, fileUris: $fileUris, appPolicy: $appPolicy, currentAppPolicy: $currentAppPolicy)';
  }
}

class ApplicationPolicy {
  ApplicationPolicy({
    required this.mode,
    required this.blacklist,
    required this.whitelist,
    required this.allowedSystemApps,
  });

  ApplicationListMode mode;

  List<String> blacklist;

  List<String> whitelist;

  List<String> allowedSystemApps;

  List<Object?> _toList() {
    return <Object?>[mode, blacklist, whitelist, allowedSystemApps];
  }

  Object encode() {
    return _toList();
  }

  static ApplicationPolicy decode(Object result) {
    result as List<Object?>;
    return ApplicationPolicy(
      mode: result[0]! as ApplicationListMode,
      blacklist: (result[1]! as List<Object?>).cast<String>(),
      whitelist: (result[2]! as List<Object?>).cast<String>(),
      allowedSystemApps: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ApplicationPolicy || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mode, other.mode) &&
        _deepEquals(blacklist, other.blacklist) &&
        _deepEquals(whitelist, other.whitelist) &&
        _deepEquals(allowedSystemApps, other.allowedSystemApps);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ApplicationPolicy(mode: $mode, blacklist: $blacklist, whitelist: $whitelist, allowedSystemApps: $allowedSystemApps)';
  }
}

class FileGrant {
  FileGrant({
    required this.uri,
    required this.name,
    required this.directory,
    required this.writable,
  });

  String uri;

  String name;

  bool directory;

  bool writable;

  List<Object?> _toList() {
    return <Object?>[uri, name, directory, writable];
  }

  Object encode() {
    return _toList();
  }

  static FileGrant decode(Object result) {
    result as List<Object?>;
    return FileGrant(
      uri: result[0]! as String,
      name: result[1]! as String,
      directory: result[2]! as bool,
      writable: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FileGrant || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(name, other.name) &&
        _deepEquals(directory, other.directory) &&
        _deepEquals(writable, other.writable);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FileGrant(uri: $uri, name: $name, directory: $directory, writable: $writable)';
  }
}

class InstalledApplication {
  InstalledApplication({
    required this.packageName,
    required this.label,
    required this.isSystem,
    required this.installedAtMs,
    required this.launchable,
    this.versionName,
    this.sizeBytes,
  });

  String packageName;

  String label;

  bool isSystem;

  int installedAtMs;

  bool launchable;

  String? versionName;

  int? sizeBytes;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      label,
      isSystem,
      installedAtMs,
      launchable,
      versionName,
      sizeBytes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static InstalledApplication decode(Object result) {
    result as List<Object?>;
    return InstalledApplication(
      packageName: result[0]! as String,
      label: result[1]! as String,
      isSystem: result[2]! as bool,
      installedAtMs: result[3]! as int,
      launchable: result[4]! as bool,
      versionName: result[5] as String?,
      sizeBytes: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InstalledApplication || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) &&
        _deepEquals(label, other.label) &&
        _deepEquals(isSystem, other.isSystem) &&
        _deepEquals(installedAtMs, other.installedAtMs) &&
        _deepEquals(launchable, other.launchable) &&
        _deepEquals(versionName, other.versionName) &&
        _deepEquals(sizeBytes, other.sizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InstalledApplication(packageName: $packageName, label: $label, isSystem: $isSystem, installedAtMs: $installedAtMs, launchable: $launchable, versionName: $versionName, sizeBytes: $sizeBytes)';
  }
}

class ExecutionConfirmation {
  ExecutionConfirmation({
    required this.runId,
    required this.toolCallId,
    required this.toolName,
    required this.summary,
    required this.arguments,
    this.targetLabel,
    required this.expiresAtMs,
  });

  String runId;

  String toolCallId;

  String toolName;

  String summary;

  Map<String, Object?> arguments;

  String? targetLabel;

  int expiresAtMs;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      toolCallId,
      toolName,
      summary,
      arguments,
      targetLabel,
      expiresAtMs,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExecutionConfirmation decode(Object result) {
    result as List<Object?>;
    return ExecutionConfirmation(
      runId: result[0]! as String,
      toolCallId: result[1]! as String,
      toolName: result[2]! as String,
      summary: result[3]! as String,
      arguments: (result[4]! as Map<Object?, Object?>).cast<String, Object?>(),
      targetLabel: result[5] as String?,
      expiresAtMs: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExecutionConfirmation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) &&
        _deepEquals(toolCallId, other.toolCallId) &&
        _deepEquals(toolName, other.toolName) &&
        _deepEquals(summary, other.summary) &&
        _deepEquals(arguments, other.arguments) &&
        _deepEquals(targetLabel, other.targetLabel) &&
        _deepEquals(expiresAtMs, other.expiresAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExecutionConfirmation(runId: $runId, toolCallId: $toolCallId, toolName: $toolName, summary: $summary, arguments: $arguments, targetLabel: $targetLabel, expiresAtMs: $expiresAtMs)';
  }
}

class TaskPanelMessage {
  TaskPanelMessage({
    required this.id,
    required this.kind,
    required this.label,
    required this.text,
  });

  String id;

  TaskPanelMessageKind kind;

  String label;

  String text;

  List<Object?> _toList() {
    return <Object?>[id, kind, label, text];
  }

  Object encode() {
    return _toList();
  }

  static TaskPanelMessage decode(Object result) {
    result as List<Object?>;
    return TaskPanelMessage(
      id: result[0]! as String,
      kind: result[1]! as TaskPanelMessageKind,
      label: result[2]! as String,
      text: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TaskPanelMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(label, other.label) &&
        _deepEquals(text, other.text);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TaskPanelMessage(id: $id, kind: $kind, label: $label, text: $text)';
  }
}

/// 有界、按实际顺序排列的最近消息，不取代消息与工具记录。
class TaskPanelSnapshot {
  TaskPanelSnapshot({
    required this.runId,
    required this.phase,
    required this.status,
    required this.messages,
    this.waitingToolCallId,
    this.userPrompt,
  });

  String runId;

  TaskPanelPhase phase;

  String status;

  List<TaskPanelMessage> messages;

  String? waitingToolCallId;

  String? userPrompt;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      phase,
      status,
      messages,
      waitingToolCallId,
      userPrompt,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TaskPanelSnapshot decode(Object result) {
    result as List<Object?>;
    return TaskPanelSnapshot(
      runId: result[0]! as String,
      phase: result[1]! as TaskPanelPhase,
      status: result[2]! as String,
      messages: (result[3]! as List<Object?>).cast<TaskPanelMessage>(),
      waitingToolCallId: result[4] as String?,
      userPrompt: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TaskPanelSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) &&
        _deepEquals(phase, other.phase) &&
        _deepEquals(status, other.status) &&
        _deepEquals(messages, other.messages) &&
        _deepEquals(waitingToolCallId, other.waitingToolCallId) &&
        _deepEquals(userPrompt, other.userPrompt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TaskPanelSnapshot(runId: $runId, phase: $phase, status: $status, messages: $messages, waitingToolCallId: $waitingToolCallId, userPrompt: $userPrompt)';
  }
}

class HostReply {
  HostReply({this.error});

  ChannelError? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static HostReply decode(Object result) {
    result as List<Object?>;
    return HostReply(error: result[0] as ChannelError?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HostReply(error: $error)';
  }
}

class SkillDirectoryImport {
  SkillDirectoryImport({
    required this.id,
    required this.maxEntries,
    required this.maxBytes,
    required this.maxFileBytes,
    required this.maxDepth,
    required this.maxPathLength,
  });

  String id;

  int maxEntries;

  int maxBytes;

  int maxFileBytes;

  int maxDepth;

  int maxPathLength;

  List<Object?> _toList() {
    return <Object?>[
      id,
      maxEntries,
      maxBytes,
      maxFileBytes,
      maxDepth,
      maxPathLength,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SkillDirectoryImport decode(Object result) {
    result as List<Object?>;
    return SkillDirectoryImport(
      id: result[0]! as String,
      maxEntries: result[1]! as int,
      maxBytes: result[2]! as int,
      maxFileBytes: result[3]! as int,
      maxDepth: result[4]! as int,
      maxPathLength: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SkillDirectoryImport || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(maxEntries, other.maxEntries) &&
        _deepEquals(maxBytes, other.maxBytes) &&
        _deepEquals(maxFileBytes, other.maxFileBytes) &&
        _deepEquals(maxDepth, other.maxDepth) &&
        _deepEquals(maxPathLength, other.maxPathLength);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SkillDirectoryImport(id: $id, maxEntries: $maxEntries, maxBytes: $maxBytes, maxFileBytes: $maxFileBytes, maxDepth: $maxDepth, maxPathLength: $maxPathLength)';
  }
}

class SkillDirectoryCopy {
  SkillDirectoryCopy({required this.path, required this.name});

  String path;

  String name;

  List<Object?> _toList() {
    return <Object?>[path, name];
  }

  Object encode() {
    return _toList();
  }

  static SkillDirectoryCopy decode(Object result) {
    result as List<Object?>;
    return SkillDirectoryCopy(
      path: result[0]! as String,
      name: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SkillDirectoryCopy || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SkillDirectoryCopy(path: $path, name: $name)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ExecutionAction) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ExecutionStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is ChannelError) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is ProgressKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is ConfirmationDecision) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is ApplicationListMode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PermissionScreen) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is TaskPanelPhase) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is TaskPanelMessageKind) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is ExecutionTarget) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionRequest) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionArtifact) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionResult) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionProgress) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionCapabilities) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionSession) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is ApplicationPolicy) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is FileGrant) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is InstalledApplication) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is ExecutionConfirmation) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is TaskPanelMessage) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is TaskPanelSnapshot) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is HostReply) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is SkillDirectoryImport) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is SkillDirectoryCopy) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExecutionAction.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExecutionStatus.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ChannelError.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ProgressKind.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConfirmationDecision.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : ApplicationListMode.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PermissionScreen.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : TaskPanelPhase.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : TaskPanelMessageKind.values[value];
      case 138:
        return ExecutionTarget.decode(readValue(buffer)!);
      case 139:
        return ExecutionRequest.decode(readValue(buffer)!);
      case 140:
        return ExecutionArtifact.decode(readValue(buffer)!);
      case 141:
        return ExecutionResult.decode(readValue(buffer)!);
      case 142:
        return ExecutionProgress.decode(readValue(buffer)!);
      case 143:
        return ExecutionCapabilities.decode(readValue(buffer)!);
      case 144:
        return ExecutionSession.decode(readValue(buffer)!);
      case 145:
        return ApplicationPolicy.decode(readValue(buffer)!);
      case 146:
        return FileGrant.decode(readValue(buffer)!);
      case 147:
        return InstalledApplication.decode(readValue(buffer)!);
      case 148:
        return ExecutionConfirmation.decode(readValue(buffer)!);
      case 149:
        return TaskPanelMessage.decode(readValue(buffer)!);
      case 150:
        return TaskPanelSnapshot.decode(readValue(buffer)!);
      case 151:
        return HostReply.decode(readValue(buffer)!);
      case 152:
        return SkillDirectoryImport.decode(readValue(buffer)!);
      case 153:
        return SkillDirectoryCopy.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ExecutionHostApi {
  /// Constructor for [ExecutionHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExecutionHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<ExecutionResult> execute(ExecutionRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.execute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ExecutionResult;
  }

  Future<void> cancel(String toolCallId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[toolCallId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<ExecutionCapabilities> queryCapabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.queryCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ExecutionCapabilities;
  }

  Future<HostReply> startRun(ExecutionSession session) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.startRun$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[session],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HostReply;
  }

  Future<void> endRun(String runId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.endRun$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[runId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setConfirmation(ExecutionConfirmation? confirmation) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.setConfirmation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[confirmation],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setTaskPanel(TaskPanelSnapshot snapshot) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionHostApi.setTaskPanel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[snapshot],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

class ExecutionSetupApi {
  /// Constructor for [ExecutionSetupApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExecutionSetupApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> exportWorkspaceFile(
    String path,
    String name,
    String mimeType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.exportWorkspaceFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path, name, mimeType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<SkillDirectoryCopy?> importSkillDirectory(
    SkillDirectoryImport request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.importSkillDirectory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as SkillDirectoryCopy?;
  }

  Future<void> cancelSkillImport(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.cancelSkillImport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<FileGrant?> selectFile(bool directory) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.selectFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[directory],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as FileGrant?;
  }

  Future<List<FileGrant>> fileGrants() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.fileGrants$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<FileGrant>();
  }

  Future<void> releaseFileGrant(String uri) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.releaseFileGrant$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<InstalledApplication>> installedApplications() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.installedApplications$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<InstalledApplication>();
  }

  Future<void> updateApplicationPolicy(ApplicationPolicy policy) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.updateApplicationPolicy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[policy],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> openPermissionSettings(PermissionScreen screen) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.ExecutionSetupApi.openPermissionSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[screen],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class ExecutionFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void progress(ExecutionProgress progress);

  void capabilityChanged(ExecutionCapabilities capabilities);

  void confirmationDecision(
    String runId,
    String toolCallId,
    ConfirmationDecision decision,
  );

  void stopRequested(String runId, String? reason);

  void continueRequested(String runId, String toolCallId);

  static void setUp(
    ExecutionFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.ExecutionFlutterApi.progress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ExecutionProgress arg_progress = args[0]! as ExecutionProgress;
          try {
            api.progress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.ExecutionFlutterApi.capabilityChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ExecutionCapabilities arg_capabilities =
              args[0]! as ExecutionCapabilities;
          try {
            api.capabilityChanged(arg_capabilities);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.ExecutionFlutterApi.confirmationDecision$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_runId = args[0]! as String;
          final String arg_toolCallId = args[1]! as String;
          final ConfirmationDecision arg_decision =
              args[2]! as ConfirmationDecision;
          try {
            api.confirmationDecision(arg_runId, arg_toolCallId, arg_decision);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.ExecutionFlutterApi.stopRequested$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_runId = args[0]! as String;
          final String? arg_reason = args[1] as String?;
          try {
            api.stopRequested(arg_runId, arg_reason);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.ExecutionFlutterApi.continueRequested$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_runId = args[0]! as String;
          final String arg_toolCallId = args[1]! as String;
          try {
            api.continueRequested(arg_runId, arg_toolCallId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
