// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum LinuxEventKind { started, stdout, stderr, exited }

class LinuxPlatformInfo {
  LinuxPlatformInfo({
    required this.rootDirectory,
    required this.abi,
    required this.available,
    required this.freeBytes,
  });

  String rootDirectory;

  String abi;

  bool available;

  int freeBytes;

  List<Object?> _toList() {
    return <Object?>[rootDirectory, abi, available, freeBytes];
  }

  Object encode() {
    return _toList();
  }

  static LinuxPlatformInfo decode(Object result) {
    result as List<Object?>;
    return LinuxPlatformInfo(
      rootDirectory: result[0]! as String,
      abi: result[1]! as String,
      available: result[2]! as bool,
      freeBytes: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LinuxPlatformInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rootDirectory, other.rootDirectory) &&
        _deepEquals(abi, other.abi) &&
        _deepEquals(available, other.available) &&
        _deepEquals(freeBytes, other.freeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LinuxPlatformInfo(rootDirectory: $rootDirectory, abi: $abi, available: $available, freeBytes: $freeBytes)';
  }
}

class LinuxProcessSpec {
  LinuxProcessSpec({
    required this.ownerId,
    required this.processId,
    required this.rootfs,
    required this.workspace,
    required this.executable,
    required this.argv,
    required this.cwd,
    required this.environment,
    this.timeoutMs,
    this.outputLimitBytes,
  });

  String ownerId;

  String processId;

  String rootfs;

  String workspace;

  String executable;

  List<String> argv;

  String cwd;

  Map<String, String> environment;

  int? timeoutMs;

  int? outputLimitBytes;

  List<Object?> _toList() {
    return <Object?>[
      ownerId,
      processId,
      rootfs,
      workspace,
      executable,
      argv,
      cwd,
      environment,
      timeoutMs,
      outputLimitBytes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LinuxProcessSpec decode(Object result) {
    result as List<Object?>;
    return LinuxProcessSpec(
      ownerId: result[0]! as String,
      processId: result[1]! as String,
      rootfs: result[2]! as String,
      workspace: result[3]! as String,
      executable: result[4]! as String,
      argv: (result[5]! as List<Object?>).cast<String>(),
      cwd: result[6]! as String,
      environment: (result[7]! as Map<Object?, Object?>).cast<String, String>(),
      timeoutMs: result[8] as int?,
      outputLimitBytes: result[9] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LinuxProcessSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ownerId, other.ownerId) &&
        _deepEquals(processId, other.processId) &&
        _deepEquals(rootfs, other.rootfs) &&
        _deepEquals(workspace, other.workspace) &&
        _deepEquals(executable, other.executable) &&
        _deepEquals(argv, other.argv) &&
        _deepEquals(cwd, other.cwd) &&
        _deepEquals(environment, other.environment) &&
        _deepEquals(timeoutMs, other.timeoutMs) &&
        _deepEquals(outputLimitBytes, other.outputLimitBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LinuxProcessSpec(ownerId: $ownerId, processId: $processId, rootfs: $rootfs, workspace: $workspace, executable: $executable, argv: $argv, cwd: $cwd, environment: $environment, timeoutMs: $timeoutMs, outputLimitBytes: $outputLimitBytes)';
  }
}

class LinuxProcessEvent {
  LinuxProcessEvent({
    required this.ownerId,
    required this.processId,
    required this.sequence,
    required this.kind,
    this.bytes,
    this.exitCode,
    this.signal,
    this.error,
    this.cancelled = false,
    this.timedOut = false,
    this.outputLimitExceeded = false,
  });

  String ownerId;

  String processId;

  int sequence;

  LinuxEventKind kind;

  Uint8List? bytes;

  int? exitCode;

  int? signal;

  String? error;

  bool cancelled;

  bool timedOut;

  bool outputLimitExceeded;

  List<Object?> _toList() {
    return <Object?>[
      ownerId,
      processId,
      sequence,
      kind,
      bytes,
      exitCode,
      signal,
      error,
      cancelled,
      timedOut,
      outputLimitExceeded,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LinuxProcessEvent decode(Object result) {
    result as List<Object?>;
    return LinuxProcessEvent(
      ownerId: result[0]! as String,
      processId: result[1]! as String,
      sequence: result[2]! as int,
      kind: result[3]! as LinuxEventKind,
      bytes: result[4] as Uint8List?,
      exitCode: result[5] as int?,
      signal: result[6] as int?,
      error: result[7] as String?,
      cancelled: result[8]! as bool,
      timedOut: result[9]! as bool,
      outputLimitExceeded: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LinuxProcessEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ownerId, other.ownerId) &&
        _deepEquals(processId, other.processId) &&
        _deepEquals(sequence, other.sequence) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(bytes, other.bytes) &&
        _deepEquals(exitCode, other.exitCode) &&
        _deepEquals(signal, other.signal) &&
        _deepEquals(error, other.error) &&
        _deepEquals(cancelled, other.cancelled) &&
        _deepEquals(timedOut, other.timedOut) &&
        _deepEquals(outputLimitExceeded, other.outputLimitExceeded);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LinuxProcessEvent(ownerId: $ownerId, processId: $processId, sequence: $sequence, kind: $kind, bytes: $bytes, exitCode: $exitCode, signal: $signal, error: $error, cancelled: $cancelled, timedOut: $timedOut, outputLimitExceeded: $outputLimitExceeded)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is LinuxEventKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is LinuxPlatformInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is LinuxProcessSpec) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is LinuxProcessEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : LinuxEventKind.values[value];
      case 130:
        return LinuxPlatformInfo.decode(readValue(buffer)!);
      case 131:
        return LinuxProcessSpec.decode(readValue(buffer)!);
      case 132:
        return LinuxProcessEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LinuxProcessHostApi {
  /// Constructor for [LinuxProcessHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LinuxProcessHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<LinuxPlatformInfo> platformInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.platformInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as LinuxPlatformInfo;
  }

  Future<void> setModes(List<String> paths, List<int> modes) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.setModes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[paths, modes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> beginTask(String ownerId, String label) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.beginTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId, label],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> endTask(String ownerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.endTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> start(LinuxProcessSpec spec) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[spec],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> writeStdin(
    String ownerId,
    String processId,
    Uint8List bytes,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.writeStdin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId, processId, bytes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> closeStdin(String ownerId, String processId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.closeStdin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId, processId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancel(String ownerId, String processId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.LinuxProcessHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId, processId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class LinuxProcessFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> event(LinuxProcessEvent event);

  void taskStopped(String ownerId);

  static void setUp(
    LinuxProcessFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.LinuxProcessFlutterApi.event$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final LinuxProcessEvent arg_event = args[0]! as LinuxProcessEvent;
          try {
            await api.event(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.LinuxProcessFlutterApi.taskStopped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_ownerId = args[0]! as String;
          try {
            api.taskStopped(arg_ownerId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
