// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.xiangyue.phase.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ExecutionApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ExecutionAction(val raw: Int) {
  LIST_APPS(0),
  OPEN_APP(1),
  INSPECT_UI(2),
  CLICK_NODE(3),
  SCROLL(4),
  INPUT_TEXT(5),
  READ_FILE(6),
  WRITE_FILE(7),
  LIST_FILES(8);

  companion object {
    fun ofRaw(raw: Int): ExecutionAction? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ExecutionStatus(val raw: Int) {
  SUCCEEDED(0),
  FAILED(1),
  CANCELLED(2);

  companion object {
    fun ofRaw(raw: Int): ExecutionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ChannelError(val raw: Int) {
  PERMISSION_REQUIRED(0),
  UNAVAILABLE(1),
  TARGET_CHANGED(2),
  INVALID_ARGUMENTS(3),
  TIMEOUT(4),
  EXECUTION_FAILED(5),
  CANCELLED(6);

  companion object {
    fun ofRaw(raw: Int): ChannelError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ProgressKind(val raw: Int) {
  STAGE(0),
  PROGRESS(1);

  companion object {
    fun ofRaw(raw: Int): ProgressKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ConfirmationDecision(val raw: Int) {
  APPROVE(0),
  REJECT(1),
  STOP(2);

  companion object {
    fun ofRaw(raw: Int): ConfirmationDecision? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ApplicationListMode(val raw: Int) {
  BLACKLIST(0),
  WHITELIST(1);

  companion object {
    fun ofRaw(raw: Int): ApplicationListMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PermissionScreen(val raw: Int) {
  NOTIFICATIONS(0),
  ACCESSIBILITY(1);

  companion object {
    fun ofRaw(raw: Int): PermissionScreen? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 机器校验的目标，不使用动作摘要代替目标身份。节点只在对应快照内有效。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExecutionTarget (
  val packageName: String? = null,
  val windowId: Long? = null,
  val snapshotId: String? = null,
  val nodeId: String? = null,
  val uri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionTarget {
      val packageName = pigeonVar_list[0] as String?
      val windowId = pigeonVar_list[1] as Long?
      val snapshotId = pigeonVar_list[2] as String?
      val nodeId = pigeonVar_list[3] as String?
      val uri = pigeonVar_list[4] as String?
      return ExecutionTarget(packageName, windowId, snapshotId, nodeId, uri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      windowId,
      snapshotId,
      nodeId,
      uri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionTarget
    return ExecutionApiPigeonUtils.deepEquals(this.packageName, other.packageName) && ExecutionApiPigeonUtils.deepEquals(this.windowId, other.windowId) && ExecutionApiPigeonUtils.deepEquals(this.snapshotId, other.snapshotId) && ExecutionApiPigeonUtils.deepEquals(this.nodeId, other.nodeId) && ExecutionApiPigeonUtils.deepEquals(this.uri, other.uri)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.windowId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.snapshotId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.nodeId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.uri)
    return result
  }
  override fun toString(): String {
    return "ExecutionTarget(packageName=$packageName, windowId=$windowId, snapshotId=$snapshotId, nodeId=$nodeId, uri=$uri)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionRequest (
  val runId: String,
  val toolCallId: String,
  val action: ExecutionAction,
  val arguments: Map<String, Any?>,
  val target: ExecutionTarget,
  val timeoutMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionRequest {
      val runId = pigeonVar_list[0] as String
      val toolCallId = pigeonVar_list[1] as String
      val action = pigeonVar_list[2] as ExecutionAction
      val arguments = pigeonVar_list[3] as Map<String, Any?>
      val target = pigeonVar_list[4] as ExecutionTarget
      val timeoutMs = pigeonVar_list[5] as Long
      return ExecutionRequest(runId, toolCallId, action, arguments, target, timeoutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runId,
      toolCallId,
      action,
      arguments,
      target,
      timeoutMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionRequest
    return ExecutionApiPigeonUtils.deepEquals(this.runId, other.runId) && ExecutionApiPigeonUtils.deepEquals(this.toolCallId, other.toolCallId) && ExecutionApiPigeonUtils.deepEquals(this.action, other.action) && ExecutionApiPigeonUtils.deepEquals(this.arguments, other.arguments) && ExecutionApiPigeonUtils.deepEquals(this.target, other.target) && ExecutionApiPigeonUtils.deepEquals(this.timeoutMs, other.timeoutMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.runId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.toolCallId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.action)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.arguments)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.target)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.timeoutMs)
    return result
  }
  override fun toString(): String {
    return "ExecutionRequest(runId=$runId, toolCallId=$toolCallId, action=$action, arguments=$arguments, target=$target, timeoutMs=$timeoutMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionArtifact (
  val uri: String,
  val name: String,
  val size: Long,
  val sha256: String? = null,
  val localPath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionArtifact {
      val uri = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val size = pigeonVar_list[2] as Long
      val sha256 = pigeonVar_list[3] as String?
      val localPath = pigeonVar_list[4] as String?
      return ExecutionArtifact(uri, name, size, sha256, localPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      name,
      size,
      sha256,
      localPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionArtifact
    return ExecutionApiPigeonUtils.deepEquals(this.uri, other.uri) && ExecutionApiPigeonUtils.deepEquals(this.name, other.name) && ExecutionApiPigeonUtils.deepEquals(this.size, other.size) && ExecutionApiPigeonUtils.deepEquals(this.sha256, other.sha256) && ExecutionApiPigeonUtils.deepEquals(this.localPath, other.localPath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.name)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.size)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.sha256)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.localPath)
    return result
  }
  override fun toString(): String {
    return "ExecutionArtifact(uri=$uri, name=$name, size=$size, sha256=$sha256, localPath=$localPath)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionResult (
  val toolCallId: String,
  val status: ExecutionStatus,
  val result: Map<String, Any?>,
  val artifacts: List<ExecutionArtifact>,
  val error: ChannelError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionResult {
      val toolCallId = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as ExecutionStatus
      val result = pigeonVar_list[2] as Map<String, Any?>
      val artifacts = pigeonVar_list[3] as List<ExecutionArtifact>
      val error = pigeonVar_list[4] as ChannelError?
      return ExecutionResult(toolCallId, status, result, artifacts, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      toolCallId,
      status,
      result,
      artifacts,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionResult
    return ExecutionApiPigeonUtils.deepEquals(this.toolCallId, other.toolCallId) && ExecutionApiPigeonUtils.deepEquals(this.status, other.status) && ExecutionApiPigeonUtils.deepEquals(this.result, other.result) && ExecutionApiPigeonUtils.deepEquals(this.artifacts, other.artifacts) && ExecutionApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.toolCallId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.status)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.result)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.artifacts)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "ExecutionResult(toolCallId=$toolCallId, status=$status, result=$result, artifacts=$artifacts, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionProgress (
  val toolCallId: String,
  val sequence: Long,
  val kind: ProgressKind,
  val payload: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionProgress {
      val toolCallId = pigeonVar_list[0] as String
      val sequence = pigeonVar_list[1] as Long
      val kind = pigeonVar_list[2] as ProgressKind
      val payload = pigeonVar_list[3] as String
      return ExecutionProgress(toolCallId, sequence, kind, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      toolCallId,
      sequence,
      kind,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionProgress
    return ExecutionApiPigeonUtils.deepEquals(this.toolCallId, other.toolCallId) && ExecutionApiPigeonUtils.deepEquals(this.sequence, other.sequence) && ExecutionApiPigeonUtils.deepEquals(this.kind, other.kind) && ExecutionApiPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.toolCallId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.sequence)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.payload)
    return result
  }
  override fun toString(): String {
    return "ExecutionProgress(toolCallId=$toolCallId, sequence=$sequence, kind=$kind, payload=$payload)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionCapabilities (
  val actions: List<ExecutionAction>,
  val notificationsAllowed: Boolean,
  val activityResumed: Boolean,
  val accessibilityConnected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionCapabilities {
      val actions = pigeonVar_list[0] as List<ExecutionAction>
      val notificationsAllowed = pigeonVar_list[1] as Boolean
      val activityResumed = pigeonVar_list[2] as Boolean
      val accessibilityConnected = pigeonVar_list[3] as Boolean
      return ExecutionCapabilities(actions, notificationsAllowed, activityResumed, accessibilityConnected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      actions,
      notificationsAllowed,
      activityResumed,
      accessibilityConnected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionCapabilities
    return ExecutionApiPigeonUtils.deepEquals(this.actions, other.actions) && ExecutionApiPigeonUtils.deepEquals(this.notificationsAllowed, other.notificationsAllowed) && ExecutionApiPigeonUtils.deepEquals(this.activityResumed, other.activityResumed) && ExecutionApiPigeonUtils.deepEquals(this.accessibilityConnected, other.accessibilityConnected)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.actions)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.notificationsAllowed)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.activityResumed)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.accessibilityConnected)
    return result
  }
  override fun toString(): String {
    return "ExecutionCapabilities(actions=$actions, notificationsAllowed=$notificationsAllowed, activityResumed=$activityResumed, accessibilityConnected=$accessibilityConnected)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionSession (
  val runId: String,
  val deviceTask: Boolean,
  val fileUris: List<String>,
  val appPolicy: ApplicationPolicy,
  val currentAppPolicy: ApplicationPolicy
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionSession {
      val runId = pigeonVar_list[0] as String
      val deviceTask = pigeonVar_list[1] as Boolean
      val fileUris = pigeonVar_list[2] as List<String>
      val appPolicy = pigeonVar_list[3] as ApplicationPolicy
      val currentAppPolicy = pigeonVar_list[4] as ApplicationPolicy
      return ExecutionSession(runId, deviceTask, fileUris, appPolicy, currentAppPolicy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runId,
      deviceTask,
      fileUris,
      appPolicy,
      currentAppPolicy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionSession
    return ExecutionApiPigeonUtils.deepEquals(this.runId, other.runId) && ExecutionApiPigeonUtils.deepEquals(this.deviceTask, other.deviceTask) && ExecutionApiPigeonUtils.deepEquals(this.fileUris, other.fileUris) && ExecutionApiPigeonUtils.deepEquals(this.appPolicy, other.appPolicy) && ExecutionApiPigeonUtils.deepEquals(this.currentAppPolicy, other.currentAppPolicy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.runId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.deviceTask)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.fileUris)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.appPolicy)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.currentAppPolicy)
    return result
  }
  override fun toString(): String {
    return "ExecutionSession(runId=$runId, deviceTask=$deviceTask, fileUris=$fileUris, appPolicy=$appPolicy, currentAppPolicy=$currentAppPolicy)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApplicationPolicy (
  val mode: ApplicationListMode,
  val blacklist: List<String>,
  val whitelist: List<String>,
  val allowedSystemApps: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApplicationPolicy {
      val mode = pigeonVar_list[0] as ApplicationListMode
      val blacklist = pigeonVar_list[1] as List<String>
      val whitelist = pigeonVar_list[2] as List<String>
      val allowedSystemApps = pigeonVar_list[3] as List<String>
      return ApplicationPolicy(mode, blacklist, whitelist, allowedSystemApps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mode,
      blacklist,
      whitelist,
      allowedSystemApps,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ApplicationPolicy
    return ExecutionApiPigeonUtils.deepEquals(this.mode, other.mode) && ExecutionApiPigeonUtils.deepEquals(this.blacklist, other.blacklist) && ExecutionApiPigeonUtils.deepEquals(this.whitelist, other.whitelist) && ExecutionApiPigeonUtils.deepEquals(this.allowedSystemApps, other.allowedSystemApps)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.mode)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.blacklist)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.whitelist)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.allowedSystemApps)
    return result
  }
  override fun toString(): String {
    return "ApplicationPolicy(mode=$mode, blacklist=$blacklist, whitelist=$whitelist, allowedSystemApps=$allowedSystemApps)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FileGrant (
  val uri: String,
  val name: String,
  val directory: Boolean,
  val writable: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FileGrant {
      val uri = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val directory = pigeonVar_list[2] as Boolean
      val writable = pigeonVar_list[3] as Boolean
      return FileGrant(uri, name, directory, writable)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      name,
      directory,
      writable,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FileGrant
    return ExecutionApiPigeonUtils.deepEquals(this.uri, other.uri) && ExecutionApiPigeonUtils.deepEquals(this.name, other.name) && ExecutionApiPigeonUtils.deepEquals(this.directory, other.directory) && ExecutionApiPigeonUtils.deepEquals(this.writable, other.writable)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.name)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.directory)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.writable)
    return result
  }
  override fun toString(): String {
    return "FileGrant(uri=$uri, name=$name, directory=$directory, writable=$writable)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstalledApplication (
  val packageName: String,
  val label: String,
  val isSystem: Boolean,
  val installedAtMs: Long,
  val launchable: Boolean,
  val versionName: String? = null,
  val sizeBytes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstalledApplication {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val isSystem = pigeonVar_list[2] as Boolean
      val installedAtMs = pigeonVar_list[3] as Long
      val launchable = pigeonVar_list[4] as Boolean
      val versionName = pigeonVar_list[5] as String?
      val sizeBytes = pigeonVar_list[6] as Long?
      return InstalledApplication(packageName, label, isSystem, installedAtMs, launchable, versionName, sizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
      isSystem,
      installedAtMs,
      launchable,
      versionName,
      sizeBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InstalledApplication
    return ExecutionApiPigeonUtils.deepEquals(this.packageName, other.packageName) && ExecutionApiPigeonUtils.deepEquals(this.label, other.label) && ExecutionApiPigeonUtils.deepEquals(this.isSystem, other.isSystem) && ExecutionApiPigeonUtils.deepEquals(this.installedAtMs, other.installedAtMs) && ExecutionApiPigeonUtils.deepEquals(this.launchable, other.launchable) && ExecutionApiPigeonUtils.deepEquals(this.versionName, other.versionName) && ExecutionApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.label)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.isSystem)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.installedAtMs)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.launchable)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.versionName)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.sizeBytes)
    return result
  }
  override fun toString(): String {
    return "InstalledApplication(packageName=$packageName, label=$label, isSystem=$isSystem, installedAtMs=$installedAtMs, launchable=$launchable, versionName=$versionName, sizeBytes=$sizeBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExecutionConfirmation (
  val runId: String,
  val toolCallId: String,
  val toolName: String,
  val summary: String,
  val arguments: Map<String, Any?>,
  val targetLabel: String? = null,
  val expiresAtMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExecutionConfirmation {
      val runId = pigeonVar_list[0] as String
      val toolCallId = pigeonVar_list[1] as String
      val toolName = pigeonVar_list[2] as String
      val summary = pigeonVar_list[3] as String
      val arguments = pigeonVar_list[4] as Map<String, Any?>
      val targetLabel = pigeonVar_list[5] as String?
      val expiresAtMs = pigeonVar_list[6] as Long
      return ExecutionConfirmation(runId, toolCallId, toolName, summary, arguments, targetLabel, expiresAtMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runId,
      toolCallId,
      toolName,
      summary,
      arguments,
      targetLabel,
      expiresAtMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExecutionConfirmation
    return ExecutionApiPigeonUtils.deepEquals(this.runId, other.runId) && ExecutionApiPigeonUtils.deepEquals(this.toolCallId, other.toolCallId) && ExecutionApiPigeonUtils.deepEquals(this.toolName, other.toolName) && ExecutionApiPigeonUtils.deepEquals(this.summary, other.summary) && ExecutionApiPigeonUtils.deepEquals(this.arguments, other.arguments) && ExecutionApiPigeonUtils.deepEquals(this.targetLabel, other.targetLabel) && ExecutionApiPigeonUtils.deepEquals(this.expiresAtMs, other.expiresAtMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.runId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.toolCallId)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.toolName)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.summary)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.arguments)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.targetLabel)
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.expiresAtMs)
    return result
  }
  override fun toString(): String {
    return "ExecutionConfirmation(runId=$runId, toolCallId=$toolCallId, toolName=$toolName, summary=$summary, arguments=$arguments, targetLabel=$targetLabel, expiresAtMs=$expiresAtMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HostReply (
  val error: ChannelError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostReply {
      val error = pigeonVar_list[0] as ChannelError?
      return HostReply(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HostReply
    return ExecutionApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ExecutionApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "HostReply(error=$error)"
  }
}
private open class ExecutionApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExecutionAction.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExecutionStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ChannelError.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProgressKind.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConfirmationDecision.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ApplicationListMode.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionScreen.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionTarget.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionArtifact.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionProgress.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionCapabilities.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionSession.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplicationPolicy.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FileGrant.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledApplication.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExecutionConfirmation.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostReply.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ExecutionAction -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ExecutionStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ChannelError -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ProgressKind -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ConfirmationDecision -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is ApplicationListMode -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionScreen -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is ExecutionTarget -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ExecutionRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ExecutionArtifact -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ExecutionResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is ExecutionProgress -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ExecutionCapabilities -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is ExecutionSession -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ApplicationPolicy -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is FileGrant -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is InstalledApplication -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is ExecutionConfirmation -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is HostReply -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ExecutionHostApi {
  suspend fun execute(request: ExecutionRequest): ExecutionResult
  fun cancel(toolCallId: String)
  fun queryCapabilities(): ExecutionCapabilities
  suspend fun startRun(session: ExecutionSession): HostReply
  fun endRun(runId: String)
  fun setConfirmation(confirmation: ExecutionConfirmation?)

  companion object {
    /** The codec used by ExecutionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExecutionApiPigeonCodec()
    }
    /** Sets up an instance of `ExecutionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ExecutionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionHostApi.execute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ExecutionRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.execute(requestArg))
              } catch (exception: Throwable) {
                ExecutionApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val toolCallIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(toolCallIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionHostApi.queryCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.queryCapabilities())
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionHostApi.startRun$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as ExecutionSession
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startRun(sessionArg))
              } catch (exception: Throwable) {
                ExecutionApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionHostApi.endRun$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val runIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.endRun(runIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionHostApi.setConfirmation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val confirmationArg = args[0] as ExecutionConfirmation?
            val wrapped: List<Any?> = try {
              api.setConfirmation(confirmationArg)
              listOf(null)
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ExecutionSetupApi {
  suspend fun selectFile(directory: Boolean): FileGrant?
  suspend fun fileGrants(): List<FileGrant>
  fun releaseFileGrant(uri: String)
  suspend fun installedApplications(): List<InstalledApplication>
  fun updateApplicationPolicy(policy: ApplicationPolicy)
  fun openPermissionSettings(screen: PermissionScreen)

  companion object {
    /** The codec used by ExecutionSetupApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExecutionApiPigeonCodec()
    }
    /** Sets up an instance of `ExecutionSetupApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ExecutionSetupApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionSetupApi.selectFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val directoryArg = args[0] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.selectFile(directoryArg))
              } catch (exception: Throwable) {
                ExecutionApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionSetupApi.fileGrants$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.fileGrants())
              } catch (exception: Throwable) {
                ExecutionApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionSetupApi.releaseFileGrant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.releaseFileGrant(uriArg)
              listOf(null)
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionSetupApi.installedApplications$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.installedApplications())
              } catch (exception: Throwable) {
                ExecutionApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionSetupApi.updateApplicationPolicy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val policyArg = args[0] as ApplicationPolicy
            val wrapped: List<Any?> = try {
              api.updateApplicationPolicy(policyArg)
              listOf(null)
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.ExecutionSetupApi.openPermissionSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val screenArg = args[0] as PermissionScreen
            val wrapped: List<Any?> = try {
              api.openPermissionSettings(screenArg)
              listOf(null)
            } catch (exception: Throwable) {
              ExecutionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ExecutionFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ExecutionFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExecutionApiPigeonCodec()
    }
  }
  suspend fun progress(progressArg: ExecutionProgress)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.phase.ExecutionFlutterApi.progress$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(progressArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ExecutionApiPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
  suspend fun capabilityChanged(capabilitiesArg: ExecutionCapabilities)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.phase.ExecutionFlutterApi.capabilityChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(capabilitiesArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ExecutionApiPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
  suspend fun confirmationDecision(runIdArg: String, toolCallIdArg: String, decisionArg: ConfirmationDecision)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.phase.ExecutionFlutterApi.confirmationDecision$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(runIdArg, toolCallIdArg, decisionArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ExecutionApiPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
  suspend fun stopRequested(runIdArg: String, reasonArg: String?)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.phase.ExecutionFlutterApi.stopRequested$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(runIdArg, reasonArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ExecutionApiPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
}
