// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.xiangyue.phase.bridge.process

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ProcessApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class LinuxEventKind(val raw: Int) {
  STARTED(0),
  STDOUT(1),
  STDERR(2),
  EXITED(3);

  companion object {
    fun ofRaw(raw: Int): LinuxEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LinuxPlatformInfo (
  val rootDirectory: String,
  val abi: String,
  val available: Boolean,
  val freeBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LinuxPlatformInfo {
      val rootDirectory = pigeonVar_list[0] as String
      val abi = pigeonVar_list[1] as String
      val available = pigeonVar_list[2] as Boolean
      val freeBytes = pigeonVar_list[3] as Long
      return LinuxPlatformInfo(rootDirectory, abi, available, freeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rootDirectory,
      abi,
      available,
      freeBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LinuxPlatformInfo
    return ProcessApiPigeonUtils.deepEquals(this.rootDirectory, other.rootDirectory) && ProcessApiPigeonUtils.deepEquals(this.abi, other.abi) && ProcessApiPigeonUtils.deepEquals(this.available, other.available) && ProcessApiPigeonUtils.deepEquals(this.freeBytes, other.freeBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.rootDirectory)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.abi)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.available)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.freeBytes)
    return result
  }
  override fun toString(): String {
    return "LinuxPlatformInfo(rootDirectory=$rootDirectory, abi=$abi, available=$available, freeBytes=$freeBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LinuxProcessSpec (
  val ownerId: String,
  val processId: String,
  val rootfs: String,
  val workspace: String,
  val executable: String,
  val argv: List<String>,
  val cwd: String,
  val environment: Map<String, String>,
  val timeoutMs: Long? = null,
  val outputLimitBytes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LinuxProcessSpec {
      val ownerId = pigeonVar_list[0] as String
      val processId = pigeonVar_list[1] as String
      val rootfs = pigeonVar_list[2] as String
      val workspace = pigeonVar_list[3] as String
      val executable = pigeonVar_list[4] as String
      val argv = pigeonVar_list[5] as List<String>
      val cwd = pigeonVar_list[6] as String
      val environment = pigeonVar_list[7] as Map<String, String>
      val timeoutMs = pigeonVar_list[8] as Long?
      val outputLimitBytes = pigeonVar_list[9] as Long?
      return LinuxProcessSpec(ownerId, processId, rootfs, workspace, executable, argv, cwd, environment, timeoutMs, outputLimitBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ownerId,
      processId,
      rootfs,
      workspace,
      executable,
      argv,
      cwd,
      environment,
      timeoutMs,
      outputLimitBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LinuxProcessSpec
    return ProcessApiPigeonUtils.deepEquals(this.ownerId, other.ownerId) && ProcessApiPigeonUtils.deepEquals(this.processId, other.processId) && ProcessApiPigeonUtils.deepEquals(this.rootfs, other.rootfs) && ProcessApiPigeonUtils.deepEquals(this.workspace, other.workspace) && ProcessApiPigeonUtils.deepEquals(this.executable, other.executable) && ProcessApiPigeonUtils.deepEquals(this.argv, other.argv) && ProcessApiPigeonUtils.deepEquals(this.cwd, other.cwd) && ProcessApiPigeonUtils.deepEquals(this.environment, other.environment) && ProcessApiPigeonUtils.deepEquals(this.timeoutMs, other.timeoutMs) && ProcessApiPigeonUtils.deepEquals(this.outputLimitBytes, other.outputLimitBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.ownerId)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.processId)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.rootfs)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.workspace)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.executable)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.argv)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.cwd)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.environment)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.timeoutMs)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.outputLimitBytes)
    return result
  }
  override fun toString(): String {
    return "LinuxProcessSpec(ownerId=$ownerId, processId=$processId, rootfs=$rootfs, workspace=$workspace, executable=$executable, argv=$argv, cwd=$cwd, environment=$environment, timeoutMs=$timeoutMs, outputLimitBytes=$outputLimitBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LinuxProcessEvent (
  val ownerId: String,
  val processId: String,
  val sequence: Long,
  val kind: LinuxEventKind,
  val bytes: ByteArray? = null,
  val exitCode: Long? = null,
  val signal: Long? = null,
  val error: String? = null,
  val cancelled: Boolean,
  val timedOut: Boolean,
  val outputLimitExceeded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LinuxProcessEvent {
      val ownerId = pigeonVar_list[0] as String
      val processId = pigeonVar_list[1] as String
      val sequence = pigeonVar_list[2] as Long
      val kind = pigeonVar_list[3] as LinuxEventKind
      val bytes = pigeonVar_list[4] as ByteArray?
      val exitCode = pigeonVar_list[5] as Long?
      val signal = pigeonVar_list[6] as Long?
      val error = pigeonVar_list[7] as String?
      val cancelled = pigeonVar_list[8] as Boolean
      val timedOut = pigeonVar_list[9] as Boolean
      val outputLimitExceeded = pigeonVar_list[10] as Boolean
      return LinuxProcessEvent(ownerId, processId, sequence, kind, bytes, exitCode, signal, error, cancelled, timedOut, outputLimitExceeded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ownerId,
      processId,
      sequence,
      kind,
      bytes,
      exitCode,
      signal,
      error,
      cancelled,
      timedOut,
      outputLimitExceeded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LinuxProcessEvent
    return ProcessApiPigeonUtils.deepEquals(this.ownerId, other.ownerId) && ProcessApiPigeonUtils.deepEquals(this.processId, other.processId) && ProcessApiPigeonUtils.deepEquals(this.sequence, other.sequence) && ProcessApiPigeonUtils.deepEquals(this.kind, other.kind) && ProcessApiPigeonUtils.deepEquals(this.bytes, other.bytes) && ProcessApiPigeonUtils.deepEquals(this.exitCode, other.exitCode) && ProcessApiPigeonUtils.deepEquals(this.signal, other.signal) && ProcessApiPigeonUtils.deepEquals(this.error, other.error) && ProcessApiPigeonUtils.deepEquals(this.cancelled, other.cancelled) && ProcessApiPigeonUtils.deepEquals(this.timedOut, other.timedOut) && ProcessApiPigeonUtils.deepEquals(this.outputLimitExceeded, other.outputLimitExceeded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.ownerId)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.processId)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.sequence)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.bytes)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.exitCode)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.signal)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.error)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.cancelled)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.timedOut)
    result = 31 * result + ProcessApiPigeonUtils.deepHash(this.outputLimitExceeded)
    return result
  }
  override fun toString(): String {
    return "LinuxProcessEvent(ownerId=$ownerId, processId=$processId, sequence=$sequence, kind=$kind, bytes=${bytes?.contentToString()}, exitCode=$exitCode, signal=$signal, error=$error, cancelled=$cancelled, timedOut=$timedOut, outputLimitExceeded=$outputLimitExceeded)"
  }
}
private open class ProcessApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LinuxEventKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LinuxPlatformInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LinuxProcessSpec.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LinuxProcessEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LinuxEventKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is LinuxPlatformInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LinuxProcessSpec -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is LinuxProcessEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LinuxProcessHostApi {
  fun platformInfo(): LinuxPlatformInfo
  suspend fun setModes(paths: List<String>, modes: List<Long>)
  suspend fun beginTask(ownerId: String, label: String)
  suspend fun endTask(ownerId: String)
  suspend fun start(spec: LinuxProcessSpec)
  suspend fun writeStdin(ownerId: String, processId: String, bytes: ByteArray)
  suspend fun closeStdin(ownerId: String, processId: String)
  suspend fun cancel(ownerId: String, processId: String)

  companion object {
    /** The codec used by LinuxProcessHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ProcessApiPigeonCodec()
    }
    /** Sets up an instance of `LinuxProcessHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LinuxProcessHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.platformInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.platformInfo())
            } catch (exception: Throwable) {
              ProcessApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.setModes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathsArg = args[0] as List<String>
            val modesArg = args[1] as List<Long>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setModes(pathsArg, modesArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.beginTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerIdArg = args[0] as String
            val labelArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.beginTask(ownerIdArg, labelArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.endTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.endTask(ownerIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val specArg = args[0] as LinuxProcessSpec
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.start(specArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.writeStdin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerIdArg = args[0] as String
            val processIdArg = args[1] as String
            val bytesArg = args[2] as ByteArray
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.writeStdin(ownerIdArg, processIdArg, bytesArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.closeStdin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerIdArg = args[0] as String
            val processIdArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.closeStdin(ownerIdArg, processIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase.LinuxProcessHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerIdArg = args[0] as String
            val processIdArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.cancel(ownerIdArg, processIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                ProcessApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LinuxProcessFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LinuxProcessFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ProcessApiPigeonCodec()
    }
  }
  suspend fun event(eventArg: LinuxProcessEvent)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.phase.LinuxProcessFlutterApi.event$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ProcessApiPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
  suspend fun taskStopped(ownerIdArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.phase.LinuxProcessFlutterApi.taskStopped$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(ownerIdArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ProcessApiPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
}
