// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum CommandEventKind { stdout, stderr, progress, exited }

class CommandChannelStatus {
  CommandChannelStatus({
    required this.channel,
    required this.state,
    required this.message,
    this.uid,
    this.revision,
    this.home,
  });

  String channel;

  String state;

  String message;

  int? uid;

  String? revision;

  String? home;

  List<Object?> _toList() {
    return <Object?>[channel, state, message, uid, revision, home];
  }

  Object encode() {
    return _toList();
  }

  static CommandChannelStatus decode(Object result) {
    result as List<Object?>;
    return CommandChannelStatus(
      channel: result[0]! as String,
      state: result[1]! as String,
      message: result[2]! as String,
      uid: result[3] as int?,
      revision: result[4] as String?,
      home: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CommandChannelStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(channel, other.channel) &&
        _deepEquals(state, other.state) &&
        _deepEquals(message, other.message) &&
        _deepEquals(uid, other.uid) &&
        _deepEquals(revision, other.revision) &&
        _deepEquals(home, other.home);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CommandChannelStatus(channel: $channel, state: $state, message: $message, uid: $uid, revision: $revision, home: $home)';
  }
}

class ExternalCommandSpec {
  ExternalCommandSpec({
    required this.ownerId,
    required this.callId,
    required this.channel,
    required this.revision,
    required this.uid,
    required this.command,
    required this.cwd,
    required this.outputLimitBytes,
  });

  String ownerId;

  String callId;

  String channel;

  String revision;

  int uid;

  String command;

  String cwd;

  int outputLimitBytes;

  List<Object?> _toList() {
    return <Object?>[
      ownerId,
      callId,
      channel,
      revision,
      uid,
      command,
      cwd,
      outputLimitBytes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExternalCommandSpec decode(Object result) {
    result as List<Object?>;
    return ExternalCommandSpec(
      ownerId: result[0]! as String,
      callId: result[1]! as String,
      channel: result[2]! as String,
      revision: result[3]! as String,
      uid: result[4]! as int,
      command: result[5]! as String,
      cwd: result[6]! as String,
      outputLimitBytes: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExternalCommandSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ownerId, other.ownerId) &&
        _deepEquals(callId, other.callId) &&
        _deepEquals(channel, other.channel) &&
        _deepEquals(revision, other.revision) &&
        _deepEquals(uid, other.uid) &&
        _deepEquals(command, other.command) &&
        _deepEquals(cwd, other.cwd) &&
        _deepEquals(outputLimitBytes, other.outputLimitBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExternalCommandSpec(ownerId: $ownerId, callId: $callId, channel: $channel, revision: $revision, uid: $uid, command: $command, cwd: $cwd, outputLimitBytes: $outputLimitBytes)';
  }
}

class ChannelTransferSpec {
  ChannelTransferSpec({
    required this.ownerId,
    required this.callId,
    required this.channel,
    required this.revision,
    required this.uid,
    required this.localRoot,
    required this.path,
    required this.remotePath,
    required this.toChannel,
    required this.fileLimitBytes,
    required this.totalLimitBytes,
    required this.entryLimit,
  });

  String ownerId;

  String callId;

  String channel;

  String revision;

  int uid;

  String localRoot;

  String path;

  String remotePath;

  bool toChannel;

  int fileLimitBytes;

  int totalLimitBytes;

  int entryLimit;

  List<Object?> _toList() {
    return <Object?>[
      ownerId,
      callId,
      channel,
      revision,
      uid,
      localRoot,
      path,
      remotePath,
      toChannel,
      fileLimitBytes,
      totalLimitBytes,
      entryLimit,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ChannelTransferSpec decode(Object result) {
    result as List<Object?>;
    return ChannelTransferSpec(
      ownerId: result[0]! as String,
      callId: result[1]! as String,
      channel: result[2]! as String,
      revision: result[3]! as String,
      uid: result[4]! as int,
      localRoot: result[5]! as String,
      path: result[6]! as String,
      remotePath: result[7]! as String,
      toChannel: result[8]! as bool,
      fileLimitBytes: result[9]! as int,
      totalLimitBytes: result[10]! as int,
      entryLimit: result[11]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ChannelTransferSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ownerId, other.ownerId) &&
        _deepEquals(callId, other.callId) &&
        _deepEquals(channel, other.channel) &&
        _deepEquals(revision, other.revision) &&
        _deepEquals(uid, other.uid) &&
        _deepEquals(localRoot, other.localRoot) &&
        _deepEquals(path, other.path) &&
        _deepEquals(remotePath, other.remotePath) &&
        _deepEquals(toChannel, other.toChannel) &&
        _deepEquals(fileLimitBytes, other.fileLimitBytes) &&
        _deepEquals(totalLimitBytes, other.totalLimitBytes) &&
        _deepEquals(entryLimit, other.entryLimit);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ChannelTransferSpec(ownerId: $ownerId, callId: $callId, channel: $channel, revision: $revision, uid: $uid, localRoot: $localRoot, path: $path, remotePath: $remotePath, toChannel: $toChannel, fileLimitBytes: $fileLimitBytes, totalLimitBytes: $totalLimitBytes, entryLimit: $entryLimit)';
  }
}

class ExternalCommandEvent {
  ExternalCommandEvent({
    required this.ownerId,
    required this.callId,
    required this.sequence,
    required this.kind,
    this.bytes,
    this.exitCode,
    this.signal,
    this.error,
    this.transferredBytes = 0,
    this.completedPaths = const [],
    this.cancelled = false,
    this.outputLimitExceeded = false,
    this.terminationAcknowledged = false,
  });

  String ownerId;

  String callId;

  int sequence;

  CommandEventKind kind;

  Uint8List? bytes;

  int? exitCode;

  int? signal;

  String? error;

  int transferredBytes;

  List<String> completedPaths;

  bool cancelled;

  bool outputLimitExceeded;

  bool terminationAcknowledged;

  List<Object?> _toList() {
    return <Object?>[
      ownerId,
      callId,
      sequence,
      kind,
      bytes,
      exitCode,
      signal,
      error,
      transferredBytes,
      completedPaths,
      cancelled,
      outputLimitExceeded,
      terminationAcknowledged,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExternalCommandEvent decode(Object result) {
    result as List<Object?>;
    return ExternalCommandEvent(
      ownerId: result[0]! as String,
      callId: result[1]! as String,
      sequence: result[2]! as int,
      kind: result[3]! as CommandEventKind,
      bytes: result[4] as Uint8List?,
      exitCode: result[5] as int?,
      signal: result[6] as int?,
      error: result[7] as String?,
      transferredBytes: result[8]! as int,
      completedPaths: (result[9]! as List<Object?>).cast<String>(),
      cancelled: result[10]! as bool,
      outputLimitExceeded: result[11]! as bool,
      terminationAcknowledged: result[12]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExternalCommandEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ownerId, other.ownerId) &&
        _deepEquals(callId, other.callId) &&
        _deepEquals(sequence, other.sequence) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(bytes, other.bytes) &&
        _deepEquals(exitCode, other.exitCode) &&
        _deepEquals(signal, other.signal) &&
        _deepEquals(error, other.error) &&
        _deepEquals(transferredBytes, other.transferredBytes) &&
        _deepEquals(completedPaths, other.completedPaths) &&
        _deepEquals(cancelled, other.cancelled) &&
        _deepEquals(outputLimitExceeded, other.outputLimitExceeded) &&
        _deepEquals(terminationAcknowledged, other.terminationAcknowledged);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExternalCommandEvent(ownerId: $ownerId, callId: $callId, sequence: $sequence, kind: $kind, bytes: $bytes, exitCode: $exitCode, signal: $signal, error: $error, transferredBytes: $transferredBytes, completedPaths: $completedPaths, cancelled: $cancelled, outputLimitExceeded: $outputLimitExceeded, terminationAcknowledged: $terminationAcknowledged)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CommandEventKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CommandChannelStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ExternalCommandSpec) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is ChannelTransferSpec) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is ExternalCommandEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CommandEventKind.values[value];
      case 130:
        return CommandChannelStatus.decode(readValue(buffer)!);
      case 131:
        return ExternalCommandSpec.decode(readValue(buffer)!);
      case 132:
        return ChannelTransferSpec.decode(readValue(buffer)!);
      case 133:
        return ExternalCommandEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CommandChannelHostApi {
  /// Constructor for [CommandChannelHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CommandChannelHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<CommandChannelStatus>> status() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<CommandChannelStatus>();
  }

  Future<void> authorize(String channel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.authorize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[channel],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> initialize(String channel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[channel],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> openSettings(String channel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.openSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[channel],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setEnabled(List<String> channels) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.setEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[channels],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> start(ExternalCommandSpec spec) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[spec],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> transfer(ChannelTransferSpec spec) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.transfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[spec],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancel(String ownerId, String callId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId, callId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> endOwner(String ownerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.phase.CommandChannelHostApi.endOwner$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class CommandChannelFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> event(ExternalCommandEvent event);

  void statusChanged();

  void ownerStopped(String ownerId);

  static void setUp(
    CommandChannelFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.CommandChannelFlutterApi.event$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ExternalCommandEvent arg_event =
              args[0]! as ExternalCommandEvent;
          try {
            await api.event(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.CommandChannelFlutterApi.statusChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.statusChanged();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.phase.CommandChannelFlutterApi.ownerStopped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_ownerId = args[0]! as String;
          try {
            api.ownerStopped(arg_ownerId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
